language: dart
dist: xenial
os: linux
dart: stable

cache:
  directories:
    - $HOME/.pub-cache

addons:
  apt:
    packages:
      - lib32stdc++6

env:
  jobs:
    - PKG=pubnub
    - PKG=pubnub_flutter FLUTTER=true
  global:
    - FLUTTER_PATH="/tmp/flutter"

install:
  - |
    if [[ $FLUTTER = "true" ]]; then
      git clone https://github.com/flutter/flutter.git -b stable "$FLUTTER_PATH"
      export PATH="$PATH:$FLUTTER_PATH/bin"
    fi
  - pub global activate derry 1.1.1

before_script:
  - cd "$TRAVIS_BUILD_DIR/$PKG"
  - if ! [[ $FLUTTER = "true" ]]; then pub get; else flutter pub get; fi

stages:
  - name: Test
    if: tag IS blank

script:
  - "derry validate analysis"
  - "derry validate formatting"
  - "derry test default"