name: Dispatched product release

on:
  workflow_dispatch:

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  id-token: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  publish:
    name: Publish package
    runs-on:
      group: organization/Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1
      - name: Publish to Pub
        uses: ./.github/.release/actions/actions/services/pub
        with:
          token: ${{ secrets.GH_TOKEN }}
