name: run_acceptance_tests

on: [push]

jobs:
  build:
    name: Perform Acceptance BDD tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Run acceptance tests
        run: |
          cd acceptance_tests
          dart pub get
          export FEATURES_PATH=../sdk-specifications/features
          dart pub run acceptance_tests
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        with:
          name: acceptance-test-reports
          path: acceptance_tests/report.xml